var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/integrations/route.js")
R.c("server/chunks/_0flf3z1._.js")
R.c("server/chunks/node_modules_next_0htnk9k._.js")
R.c("server/chunks/013__@neondatabase_serverless_index_0um0t_i.js")
R.c("server/chunks/node_modules_@clerk_shared_dist_runtime_13zpi7q._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_01-8k2s._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_06sp1yh._.js")
R.c("server/chunks/node_modules_ioredis_built_0kn.sqb._.js")
R.c("server/chunks/node_modules_@upstash_redis_0id.qid._.js")
R.c("server/chunks/[root-of-the-server]__0s-75_~._.js")
R.c("server/chunks/[root-of-the-server]__0y.z97n._.js")
R.c("server/chunks/apps_dashboard__next-internal_server_app_api_integrations_route_actions_02f3liy.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/dashboard/src/app/api/integrations/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/dashboard/src/app/api/integrations/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
