client_id = "d895bed09fae035e6177ee9d34eff219"
name = "shopkeeper-production"
application_url = "https://app.useshopkeeper.com"
embedded = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "orders/create", "orders/fulfilled", "orders/updated", "orders/cancelled", "app/uninstalled" ]
uri = "https://clerk-production-e37f.up.railway.app/webhooks/shopify"

[access_scopes]
scopes = "read_customers,write_customers,write_discounts,write_gift_cards,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_order_edits,read_orders,write_orders,read_products,read_returns,write_returns,read_content,write_store_credit_account_transactions,read_store_credit_accounts,write_app_proxy"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://dashboard-shopkeeper.vercel.app/api/integrations/shopify/callback",
  "https://app.useshopkeeper.com/api/integrations/shopify/callback"
]

[app_proxy]
url = "https://app.useshopkeeper.com/api/storefront-chat/proxy"
subpath = "shopkeeper-chat"
prefix = "apps"
