// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/create-workspace" | "/dashboard" | "/dashboard/agent" | "/dashboard/customers" | "/dashboard/integrations" | "/dashboard/integrations/oauth/complete" | "/dashboard/kb" | "/dashboard/orders" | "/dashboard/review" | "/dashboard/settings" | "/dashboard/team" | "/dashboard/tickets" | "/demo-film" | "/login" | "/onboarding" | "/privacy" | "/select-org" | "/signup" | "/terms"
type AppRouteHandlerRoutes = "/api/agent" | "/api/agent/actions" | "/api/agent/actions/feedback" | "/api/agent/ask" | "/api/agent/autonomy-readiness" | "/api/agent/chat" | "/api/agent/io-send-internal" | "/api/agent/plan" | "/api/agent/quick-approve" | "/api/agent/sessions" | "/api/agent/sessions/[id]" | "/api/agent/voice" | "/api/ai/summary" | "/api/attachments" | "/api/billing" | "/api/billing/checkout" | "/api/billing/portal" | "/api/billing/webhook" | "/api/health" | "/api/home-summary" | "/api/integrations" | "/api/integrations/[id]" | "/api/integrations/gmail/auth" | "/api/integrations/gmail/callback" | "/api/integrations/instagram/auth" | "/api/integrations/instagram/callback" | "/api/integrations/instagram/connect" | "/api/integrations/outlook/auth" | "/api/integrations/outlook/callback" | "/api/integrations/shopify/auth" | "/api/integrations/shopify/callback" | "/api/integrations/shopify/kb-sync" | "/api/integrations/telegram" | "/api/kb" | "/api/kb/[id]" | "/api/kb/bases" | "/api/kb/bases/[id]" | "/api/kb/bases/[id]/articles" | "/api/messages" | "/api/messages/auto-ack" | "/api/messages/internal" | "/api/messages/retry" | "/api/orders" | "/api/org" | "/api/org/data" | "/api/org/gdpr-export" | "/api/search" | "/api/shopify/customer" | "/api/shopify/customers" | "/api/shopify/customers/search" | "/api/team" | "/api/threads" | "/api/threads/[id]" | "/api/threads/[id]/presence" | "/api/threads/bulk" | "/api/threads/customer/[customerId]" | "/api/threads/shopify" | "/api/webhooks/clerk" | "/api/webhooks/email" | "/api/webhooks/meta"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = "/dashboard/activity" | "/dashboard/reports"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/agent": {}
  "/api/agent/actions": {}
  "/api/agent/actions/feedback": {}
  "/api/agent/ask": {}
  "/api/agent/autonomy-readiness": {}
  "/api/agent/chat": {}
  "/api/agent/io-send-internal": {}
  "/api/agent/plan": {}
  "/api/agent/quick-approve": {}
  "/api/agent/sessions": {}
  "/api/agent/sessions/[id]": { "id": string; }
  "/api/agent/voice": {}
  "/api/ai/summary": {}
  "/api/attachments": {}
  "/api/billing": {}
  "/api/billing/checkout": {}
  "/api/billing/portal": {}
  "/api/billing/webhook": {}
  "/api/health": {}
  "/api/home-summary": {}
  "/api/integrations": {}
  "/api/integrations/[id]": { "id": string; }
  "/api/integrations/gmail/auth": {}
  "/api/integrations/gmail/callback": {}
  "/api/integrations/instagram/auth": {}
  "/api/integrations/instagram/callback": {}
  "/api/integrations/instagram/connect": {}
  "/api/integrations/outlook/auth": {}
  "/api/integrations/outlook/callback": {}
  "/api/integrations/shopify/auth": {}
  "/api/integrations/shopify/callback": {}
  "/api/integrations/shopify/kb-sync": {}
  "/api/integrations/telegram": {}
  "/api/kb": {}
  "/api/kb/[id]": { "id": string; }
  "/api/kb/bases": {}
  "/api/kb/bases/[id]": { "id": string; }
  "/api/kb/bases/[id]/articles": { "id": string; }
  "/api/messages": {}
  "/api/messages/auto-ack": {}
  "/api/messages/internal": {}
  "/api/messages/retry": {}
  "/api/orders": {}
  "/api/org": {}
  "/api/org/data": {}
  "/api/org/gdpr-export": {}
  "/api/search": {}
  "/api/shopify/customer": {}
  "/api/shopify/customers": {}
  "/api/shopify/customers/search": {}
  "/api/team": {}
  "/api/threads": {}
  "/api/threads/[id]": { "id": string; }
  "/api/threads/[id]/presence": { "id": string; }
  "/api/threads/bulk": {}
  "/api/threads/customer/[customerId]": { "customerId": string; }
  "/api/threads/shopify": {}
  "/api/webhooks/clerk": {}
  "/api/webhooks/email": {}
  "/api/webhooks/meta": {}
  "/create-workspace": {}
  "/dashboard": {}
  "/dashboard/activity": {}
  "/dashboard/agent": {}
  "/dashboard/customers": {}
  "/dashboard/integrations": {}
  "/dashboard/integrations/oauth/complete": {}
  "/dashboard/kb": {}
  "/dashboard/orders": {}
  "/dashboard/reports": {}
  "/dashboard/review": {}
  "/dashboard/settings": {}
  "/dashboard/team": {}
  "/dashboard/tickets": {}
  "/demo-film": {}
  "/login": {}
  "/onboarding": {}
  "/privacy": {}
  "/select-org": {}
  "/signup": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
