// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(auth)/create-workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-workspace">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/create-workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/select-org/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-org">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/select-org/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(marketing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(marketing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(marketing)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/(marketing)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(marketing)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/(marketing)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(onboarding)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/(onboarding)/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/account">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/agent/configure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agent/configure">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/agent/configure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agent">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/integrations">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/kb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/kb">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/kb/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/review">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/team">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tickets">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/integrations/oauth/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/integrations/oauth/complete">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/integrations/oauth/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/demo-film/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-film">> = Specific
  const handler = {} as typeof import("../../../src/app/demo-film/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/actions/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/actions/feedback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/actions/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/actions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/answer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/answer">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/answer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/ask/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/ask">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/ask/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/autonomy-readiness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/autonomy-readiness">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/autonomy-readiness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/io-send-internal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/io-send-internal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/io-send-internal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/plan">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/quick-approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/quick-approve">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/quick-approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/sessions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/sessions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/voice">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attachments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing">> = Specific
  const handler = {} as typeof import("../../../src/app/api/billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/billing/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/billing/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/home-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home-summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/home-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/gmail/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/gmail/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/gmail/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/gmail/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/gmail/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/gmail/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/instagram/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/instagram/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/instagram/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/instagram/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/instagram/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/instagram/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/instagram/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/instagram/connect">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/instagram/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/outlook/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/outlook/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/outlook/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/outlook/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/outlook/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/outlook/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/shopify/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/shopify/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/shopify/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/shopify/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/shopify/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/shopify/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/shopify/kb-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/shopify/kb-sync">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/shopify/kb-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/telegram/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/telegram">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/telegram/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/kb/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kb/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/kb/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/kb/bases/[id]/articles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kb/bases/[id]/articles">> = Specific
  const handler = {} as typeof import("../../../src/app/api/kb/bases/[id]/articles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/kb/bases/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kb/bases/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/kb/bases/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/kb/bases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kb/bases">> = Specific
  const handler = {} as typeof import("../../../src/app/api/kb/bases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/kb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kb">> = Specific
  const handler = {} as typeof import("../../../src/app/api/kb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/messages/auto-ack/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/auto-ack">> = Specific
  const handler = {} as typeof import("../../../src/app/api/messages/auto-ack/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/messages/internal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/internal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/messages/internal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/messages/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/retry">> = Specific
  const handler = {} as typeof import("../../../src/app/api/messages/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/org/data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/data">> = Specific
  const handler = {} as typeof import("../../../src/app/api/org/data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/org/gdpr-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/gdpr-export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/org/gdpr-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/org/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org">> = Specific
  const handler = {} as typeof import("../../../src/app/api/org/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/customer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/customer">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/customer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/customers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/customers/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/customers/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/customers/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team">> = Specific
  const handler = {} as typeof import("../../../src/app/api/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/threads/[id]/presence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads/[id]/presence">> = Specific
  const handler = {} as typeof import("../../../src/app/api/threads/[id]/presence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/threads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/threads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/threads/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads/bulk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/threads/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/threads/customer/[customerId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads/customer/[customerId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/threads/customer/[customerId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads">> = Specific
  const handler = {} as typeof import("../../../src/app/api/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/threads/shopify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads/shopify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/threads/shopify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/clerk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/clerk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/clerk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/email">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/meta">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(onboarding)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(onboarding)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/(shell)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/(shell)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/integrations/oauth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/integrations/oauth">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/integrations/oauth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
