import { parseOutboundMessageId } from './reply.js';
import type { ParsedEmail } from './types.js';

// Bounces are generated by the receiving mail system, never by a person. A real
// customer is never at one of these addresses, which is what keeps the
// Message-ID check below from misreading an ordinary reply as a bounce — an
// ordinary reply quotes our Message-ID in References too.
const DAEMON_LOCAL_PARTS = new Set(['mailer-daemon', 'postmaster']);

// RFC 3463 status: 5.x.x is permanent, 4.x.x is transient.
const DSN_STATUS_PATTERN = /\b([45])\.\d{1,3}\.\d{1,3}\b/;
const DIAGNOSTIC_PATTERN = /^diagnostic-code:\s*(.+)$/im;

export interface DetectedBounce {
  // Our own Message.id, recovered from the RFC Message-ID the report quotes.
  outboundMessageId: string;
  detail: string | null;
  permanent: boolean;
}

function isDaemonSender(from: string | null): boolean {
  if (!from) return false;
  const local = from.toLowerCase().split('@')[0];
  return DAEMON_LOCAL_PARTS.has(local);
}

function firstOutboundMessageId(parsed: ParsedEmail): string | null {
  const candidates = [parsed.inReplyTo, ...parsed.references];
  for (const candidate of candidates) {
    const id = parseOutboundMessageId(candidate);
    if (id) return id;
  }
  return null;
}

function extractDetail(body: string): string | null {
  const diagnostic = DIAGNOSTIC_PATTERN.exec(body);
  if (diagnostic) return diagnostic[1].trim().slice(0, 500);
  return null;
}

// Recognizes a delivery status notification for a message we sent.
//
// Returns null for anything it cannot attribute. A bounce it fails to recognize
// leaves the thread looking answered, which is bad; but a reply it wrongly calls
// a bounce would drop a real customer message, which is worse. So both halves —
// daemon sender and a recoverable outbound Message-ID — are required.
export function detectEmailBounce(parsed: ParsedEmail): DetectedBounce | null {
  if (!isDaemonSender(parsed.from)) return null;

  const outboundMessageId = firstOutboundMessageId(parsed);
  if (!outboundMessageId) return null;

  const body = `${parsed.text ?? ''}\n${parsed.subject ?? ''}`;
  const status = DSN_STATUS_PATTERN.exec(body);

  return {
    outboundMessageId,
    detail: extractDetail(parsed.text ?? ''),
    // Absent an explicit 4.x.x transient status, treat it as permanent: telling
    // the merchant a delivery failed that later succeeds is a smaller harm than
    // staying quiet about one that never will.
    permanent: status ? status[1] === '5' : true,
  };
}
