var R=require("./chunks/[turbopack]_runtime.js")("server/middleware.js")
R.c("server/chunks/node_modules_next_headers_0q6k800.js")
R.c("server/chunks/node_modules_next_0rsi991._.js")
R.c("server/chunks/node_modules_@clerk_shared_dist_runtime_0wbjg~j._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_0cv-ixo._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_0oqjc11._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_13x0s1z._.js")
R.c("server/chunks/[root-of-the-server]__0dgs4uo._.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/middleware.js { INNER_MIDDLEWARE_MODULE => \"[project]/apps/dashboard/src/proxy.ts [middleware] (ecmascript)\" } [middleware] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/middleware.js { INNER_MIDDLEWARE_MODULE => \"[project]/apps/dashboard/src/proxy.ts [middleware] (ecmascript)\" } [middleware] (ecmascript)").exports
