var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/threads/[id]/presence/route.js")
R.c("server/chunks/_0ebk~.0._.js")
R.c("server/chunks/node_modules_next_0ox4-3r._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_03q_w41._.js")
R.c("server/chunks/node_modules_@upstash_redis_0id.qid._.js")
R.c("server/chunks/node_modules_12g_wuj._.js")
R.c("server/chunks/[root-of-the-server]__0-2b_3-._.js")
R.c("server/chunks/0.l-__next-internal_server_app_api_threads_[id]_presence_route_actions_02p1uhv.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/dashboard/src/app/api/threads/[id]/presence/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/dashboard/src/app/api/threads/[id]/presence/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
